"""Write the conformance kit's reproducibility manifest and its traceability matrix.

Two artifacts, both generated so neither can drift:

  MANIFEST.json      exact digests of every file the conformance kit consists of
  traceability.md    requirement -> profile -> fixtures -> runner -> witness -> documentation

Traceability is the audit that matters. A requirement stated in prose and witnessed by nothing is
decoration, and a fixture asserting something the contract never required is the runner inventing
a standard. Both are failures, and this tool makes both visible.
"""

import hashlib
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ROOT = REPO / "conformance" / "decision-replay-v1"
DOCS = REPO / "docs" / "conformance"

KIT = [
    "docs/conformance/decision-replay-v1.md",
    "docs/conformance/implementation-guide.md",
    "docs/conformance/claims.md",
    "conformance/decision-replay-v1/profile.json",
    "conformance/decision-replay-v1/result.schema.json",
    "conformance/decision-replay-v1/adapter-protocol.md",
    "conformance/decision-replay-v1/fixtures/manifest.json",
    "tools/run_conformance.py",
    "tools/conformance_adapter.py",
    "tools/build_conformance_fixtures.py",
    "tools/build_conformance_manifest.py",
    "tools/build_conformance_manifest_of_record.py",
    "tests/test_conformance.py",
]

# Which hostile stub in tests/test_conformance.py proves the runner detects a violation.
STUB_FOR = {
    "DR-2.3": "maps-hold-to-block", "DR-2.4": "maps-error-to-block",
    "DR-2.5": "defaults-allow", "DR-6.1": "signs-but-cannot-recompute",
    "DR-4.5": "ignores-altered-candidate-binding", "DR-4.6": "verifies-database-verdict-only",
    "DR-5.1": "trusts-unknown-key", "DR-5.2": "trusts-unknown-key",
    "DR-6.5": "rejects-expired-allow", "DR-6.6": "rejects-expired-allow",
    "DR-7.2": "ignores-altered-acknowledgment", "DR-1.3": "verifies-database-verdict-only",
}


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def build():
    document = (DOCS / "decision-replay-v1.md").read_text(encoding="utf-8")
    manifest = json.loads((ROOT / "fixtures" / "manifest.json").read_text(encoding="utf-8"))
    profile = json.loads((ROOT / "profile.json").read_text(encoding="utf-8"))

    stated = re.findall(r"\*\*(DR-\d+\.\d+)\*\* ([A-Za-z].*?)(?=\n)", document)
    levels = {}
    for identifier, text in stated:
        level = "MUST NOT" if " MUST NOT " in " " + text else (
            "MUST" if " MUST " in " " + text else (
                "SHOULD" if " SHOULD " in " " + text else "MAY"))
        levels[identifier] = (level, text.strip())

    by_requirement = {}
    for fixture in manifest["fixtures"]:
        for requirement in fixture["requirements"]:
            by_requirement.setdefault(requirement, {"positive": [], "negative": []})
            by_requirement[requirement][
                "positive" if fixture["polarity"] == "positive" else "negative"
            ].append(fixture["fixture_id"])

    rows = []
    for identifier in sorted(levels, key=lambda k: [int(n) for n in k[3:].split(".")]):
        level, text = levels[identifier]
        entry = by_requirement.get(identifier, {"positive": [], "negative": []})
        rows.append({
            "requirement": identifier,
            "level": level,
            "statement": text,
            "positive_fixtures": entry["positive"],
            "negative_fixtures": entry["negative"],
            "hostile_stub": STUB_FOR.get(identifier),
            "in_machine_profile": identifier in profile["requirements_covered"],
        })

    lines = [
        "# Traceability matrix — Decision Replay Conformance Profile v1",
        "",
        "Generated by `tools/build_conformance_manifest_of_record.py`. Every MUST and MUST NOT is",
        "traced from the normative statement to the fixtures that witness it and, where the",
        "violation is one an implementation could fake, to the hostile stub that proves the runner",
        "detects it.",
        "",
        "A requirement with no witness is decoration. A fixture asserting something the contract",
        "never stated would be the runner inventing a standard. Neither is present below, and",
        "`tests/test_conformance.py` fails the build if either appears.",
        "",
        "| Requirement | Level | Positive | Negative | Hostile stub | In machine profile |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        positive = ", ".join(f.split("/", 1)[1] for f in row["positive_fixtures"]) or "—"
        negative = ("%d bundles" % len(row["negative_fixtures"])) \
            if len(row["negative_fixtures"]) > 3 else \
            (", ".join(f.split("/", 1)[1] for f in row["negative_fixtures"]) or "—")
        lines.append("| %s | %s | %s | %s | %s | %s |" % (
            row["requirement"], row["level"], positive, negative,
            row["hostile_stub"] or "—", "yes" if row["in_machine_profile"] else "no"))

    uncovered = [r["requirement"] for r in rows
                 if not r["positive_fixtures"] and not r["negative_fixtures"]]
    lines += ["", "## Requirements without a fixture", ""]
    if uncovered:
        for identifier in uncovered:
            lines.append("- **%s** — see the normative document, which states why." % identifier)
    else:
        lines.append("- none")
    lines += ["", "## Statements", ""]
    for row in rows:
        lines.append("- **%s** (%s) %s" % (row["requirement"], row["level"], row["statement"]))
    lines.append("")
    (DOCS / "traceability.md").write_text("\n".join(lines), encoding="utf-8")

    record = {
        "profile_id": profile["profile_id"],
        "profile_version": profile["profile_version"],
        "note": "Exact identity of every file the conformance kit consists of. A result is only "
                "meaningful against the fixture-manifest digest it names; this record makes the "
                "rest of the kit checkable the same way.",
        "files": [{"file": name, "sha256": sha(REPO / name)} for name in KIT],
        "fixture_bundles": [
            {"bundle": fixture["bundle"], "fixture_id": fixture["fixture_id"],
             "files": fixture["files"], "derived_from": fixture["derived_from"]}
            for fixture in manifest["fixtures"]],
        "requirement_count": len(rows),
        "fixture_count": len(manifest["fixtures"]),
    }
    (ROOT / "MANIFEST.json").write_text(
        json.dumps(record, indent=1, sort_keys=True) + "\n", encoding="utf-8")

    print("requirements traced : %d" % len(rows))
    print("without a fixture   : %s" % (", ".join(uncovered) or "none"))
    print("kit files recorded  : %d" % len(KIT))
    print("fixture bundles     : %d" % len(manifest["fixtures"]))


if __name__ == "__main__":
    build()
